theme: jekyll-theme-cayman
defaults:
  -
    scope:
      path: ""
    values:
      payment_method: "0:銀行振込 1:クレジットカード 2:バンクチェック <br> 3:RP口座振替 4:RL口座振替 5:その他口座振替 <br> 6:コンビニ払込票(A4) 7:コンビニ払込票(ハガキ) 9:バーチャル口座 <br> 10:その他決済1 11:その他決済2 12:その他決済3 <br> 13:その他決済4 14:その他決済5"