version: '3.7'
services:
  app:
    image: jekyll/jekyll:pages
    command: bash -c "gem install webrick && jekyll serve --force_polling"
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - 4000:4000
